# Generated by Django 2.2.1 on 2019-11-27 09:48

from django.db import migrations, models
import django.contrib.postgres
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS hstore"),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docID', models.IntegerField()),
                ('document', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InvertedIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('list', django.contrib.postgres.fields.HStoreField(default=dict)),
            ],
        ),
    ]
