# Generated by Django 2.2.1 on 2019-11-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='docID',
        ),
    ]
