# Generated by Django 2.2.1 on 2019-11-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_documents_docid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.CharField(max_length=1000),
        ),
    ]
